2025-08-26 22:24:10,934 INFO    MainThread:33674 [wandb_setup.py:_flush():76] Current SDK version is 0.16.4
2025-08-26 22:24:10,935 INFO    MainThread:33674 [wandb_setup.py:_flush():76] Configure stats pid to 33674
2025-08-26 22:24:10,935 INFO    MainThread:33674 [wandb_setup.py:_flush():76] Loading settings from /home/dean/.config/wandb/settings
2025-08-26 22:24:10,935 INFO    MainThread:33674 [wandb_setup.py:_flush():76] Loading settings from /home/dean/nd0821-c2-build-model-workflow-exercises/nd0821-c2-build-model-workflow-exercises-1/lesson-5-final-pipeline-release-and-deploy/exercises/exercise_14/solution/check_data/wandb/settings
2025-08-26 22:24:10,935 INFO    MainThread:33674 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'run_group': 'dev', 'project': 'exercise_14'}
2025-08-26 22:24:10,935 INFO    MainThread:33674 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2025-08-26 22:24:10,935 WARNING MainThread:33674 [wandb_setup.py:_flush():76] Could not save program above cwd: /home/dean/miniconda3/envs/mlflow-60000e2b97642ccc38c7a9ee503977f0abd54819/bin/pytest
2025-08-26 22:24:10,935 INFO    MainThread:33674 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': None, 'program_abspath': '/home/dean/miniconda3/envs/mlflow-60000e2b97642ccc38c7a9ee503977f0abd54819/bin/pytest', 'program': '/home/dean/miniconda3/envs/mlflow-60000e2b97642ccc38c7a9ee503977f0abd54819/bin/pytest'}
2025-08-26 22:24:10,936 INFO    MainThread:33674 [wandb_init.py:_log_setup():526] Logging user logs to /home/dean/nd0821-c2-build-model-workflow-exercises/nd0821-c2-build-model-workflow-exercises-1/lesson-5-final-pipeline-release-and-deploy/exercises/exercise_14/solution/check_data/wandb/run-20250826_222410-1yqw36fs/logs/debug.log
2025-08-26 22:24:10,936 INFO    MainThread:33674 [wandb_init.py:_log_setup():527] Logging internal logs to /home/dean/nd0821-c2-build-model-workflow-exercises/nd0821-c2-build-model-workflow-exercises-1/lesson-5-final-pipeline-release-and-deploy/exercises/exercise_14/solution/check_data/wandb/run-20250826_222410-1yqw36fs/logs/debug-internal.log
2025-08-26 22:24:10,936 INFO    MainThread:33674 [wandb_init.py:init():566] calling init triggers
2025-08-26 22:24:10,936 INFO    MainThread:33674 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2025-08-26 22:24:10,936 INFO    MainThread:33674 [wandb_init.py:init():616] starting backend
2025-08-26 22:24:10,936 INFO    MainThread:33674 [wandb_init.py:init():620] setting up manager
2025-08-26 22:24:10,938 INFO    MainThread:33674 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-08-26 22:24:10,942 INFO    MainThread:33674 [wandb_init.py:init():628] backend started and connected
2025-08-26 22:24:10,945 INFO    MainThread:33674 [wandb_init.py:init():720] updated telemetry
2025-08-26 22:24:10,952 INFO    MainThread:33674 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2025-08-26 22:24:11,299 INFO    MainThread:33674 [wandb_run.py:_on_init():2262] communicating current version
2025-08-26 22:24:11,468 INFO    MainThread:33674 [wandb_run.py:_on_init():2271] got version response upgrade_message: "wandb version 0.21.1 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2025-08-26 22:24:11,468 INFO    MainThread:33674 [wandb_init.py:init():804] starting run threads in backend
2025-08-26 22:24:12,862 INFO    MainThread:33674 [wandb_run.py:_console_start():2241] atexit reg
2025-08-26 22:24:12,862 INFO    MainThread:33674 [wandb_run.py:_redirect():2096] redirect: wrap_raw
2025-08-26 22:24:12,862 INFO    MainThread:33674 [wandb_run.py:_redirect():2161] Wrapping output streams.
2025-08-26 22:24:12,862 INFO    MainThread:33674 [wandb_run.py:_redirect():2186] Redirects installed.
2025-08-26 22:24:12,864 INFO    MainThread:33674 [wandb_init.py:init():847] run started, returning control to user process
2025-08-26 22:24:19,279 WARNING MsgRouterThr:33674 [router.py:message_loop():77] message_loop has been closed
